package questions;

import main.Question;

public class Q2 extends Question {
//	Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//	By starting with 1 and 2, the first 10 terms will be:
//		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//	By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//	find the sum of the even-valued terms.

	public Q2(int i) {
		super(i);
	}
	
	public void execute() {
		int sum = evenFibonacci(4000000);
		printAnswer(sum);
	}
	
	private int evenFibonacci(int upperEnd) {
		int sum = 2;
		int n1 = 1;
		int n2 = 2;
		
		while(true) {
			int n3 = n1 + n2;
			n1 = n2;
			n2 = n3;
			
			if(n3 >= upperEnd) break;
			
			if(n3 % 2 == 0) sum += n3;
		}
		
		return sum;
	}
}
